version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    networks:
        - elastic

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    ports:
        - 9200:9200
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
        - xpack.security.enabled=false
        - ELASTIC_PASSWORD=admin@123
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    networks:
        - elastic
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.14.1
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
        - ELASTICSEARCH_URL=elastic:9200
    networks:
        - elastic
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    
